"""HTTP request/response logging middleware."""

import logging
import time

from starlette.types import ASGIApp, Message, Receive, Scope, Send

logger = logging.getLogger("app.requests")


class LoggingMiddleware:
    """Logs method, path, status code, and duration for every HTTP request.

    Implemented as pure ASGI middleware rather than Starlette's
    BaseHTTPMiddleware. BaseHTTPMiddleware runs the downstream app in a
    separate task and streams the response back through an internal anyio
    memory object stream; combined with a custom global exception handler
    (AppError -> JSONResponse) and pytest-asyncio's per-test event loop,
    that produced "Future attached to a different loop" errors specifically
    on responses generated by the exception handler. Pure ASGI middleware
    talks to (scope, receive, send) directly and sidesteps that machinery
    entirely -- this is also what Starlette's own docs recommend
    BaseHTTPMiddleware users switch to when they hit its documented
    limitations.
    """

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        method = scope["method"]
        path = scope["path"]
        start_time = time.perf_counter()
        status_code = None

        async def send_wrapper(message: Message) -> None:
            nonlocal status_code
            if message["type"] == "http.response.start":
                status_code = message["status"]
            await send(message)

        await self.app(scope, receive, send_wrapper)

        duration_ms = (time.perf_counter() - start_time) * 1000
        logger.info("%s %s -> %s (%.2fms)", method, path, status_code, duration_ms)